### ISSUE TITLE
No response after calling sendPayment

### ISSUE THREAD

**Issue by hakonamatata** [altangent/lnd-async#11]
Hi, thanks for this project, it's very helpful!

I have used lnd-async to receive payment requests and automatically payout satoshi. 

But sometimes nothing happens here: 

```
  // attempt to send payment
  let call = lnd.client.sendPayment({});
  call.write({
    payment_request,
  });

  call.on('data', function (payment) {  // never called?

    if (payment['payment_error']) {

      // error 
      // return credits back to user

      return;

    }

    // credits subtracted
    // satoshi paid out
    // all is good

  });
```

I don't get a "success" response and I don't get an "error" response. 

Not sure what is happening, is it timing out? Can I assume the payout failed and return an error or how can I securely handle this? thanks

I am running lnd 0.5-beta-rc1 btw. I know this is not officially supported.

**Comment by hakonamatata** [comment]
After some debugging I can see that this happens when "local_balance" is less then the requested amount in the invoice. Then nothing happens, or it times out.

**Comment by bmancini55** [comment]
Do you have `end`, `error`, or `status` events in place?  If so, are they providing any additional information?

grpc has additional events for stream methods:
https://grpc.io/docs/tutorials/basic/node.html#streaming-rpcs

**Comment by hakonamatata** [comment]
Tried adding that now, that also does not pick up anything

If I try to pay an invoice again, manually with lncli, without having enough local funds, I just get: 

```
{
        "payment_error": "payment is in transition",
        "payment_preimage": "",
        "payment_route": null
}
```

I would prefer if lnd just attempted to pay the invoice and if it failed after 20 sec, the payment was set to failed and returned "payment failed, not enough local funds" or something. 

But I guess this has more to do with the implementation of lnd and not your integration.

**Comment by ranchalp** [comment]
This error comes when the same hash has been used twice. Try changing the hash.

**Comment by bmancini55** [comment]
Closing this due to no updates.
