### ISSUE TITLE
Proto file is old - please update it!

### ISSUE THREAD

**Issue by LNBIG-COM** [altangent/lnd-async#16]
Hello!

I tried to use OpenChannelSync with "spend_unconfirmed" but the LND don't do it.
After researching i see that your module has old proto

For example, your proto:

https://github.com/altangent/lnd-async/blob/master/lib/rpc.proto#L1143

The original now is:

https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L1249

There is the new field https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L1281

**Comment by bmancini55** [comment]
Thanks!  Pushed version 1.6.0 with the new proto file.
